apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: guestbook-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8182 # port i'm exposing locally
      targetPort: 80 # port that loadbalancer attaching to