apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guestbook-frontend-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-frontend
  template:
    metadata:
      labels:
        app: guestbook-frontend
    spec:
      containers:
        - name: guestbook-frontend
          image: docker.artifactory.euw.platformservices.io/bpe/guestbook-frontend:1.0.2
          ports:
          - containerPort: 88
          env:
          - name: REDIS_MASTER_SERVICE_HOST
            value: redis-master
          - name: REDIS_SLAVE_SERVICE_HOST
            value: redis-master
