apiVersion: v1
kind: Pod
metadata:
  name: guestbook-frontend
spec:
  containers:
    - name: guestbook-frontend
      image: docker.artifactory.euw.platformservices.io/bpe/guestbook-frontend:1.0.2
      ports:
      - containerPort: 88