apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-frontend
  template:
    metadata:
      labels:
        app: guestbook-frontend
    spec:
      containers:
        - name: guestbook-frontend
          image: docker.artifactory.euw.platformservices.io/bpe/guestbook-frontend:1.0.2
          ports:
          - containerPort: 88
          volumeMounts:
            - mountPath: /config
              name: config-volume
          env:
          - name: CONFIG_FILE
            value: /config/config.json
          # - name: REDIS_MASTER_SERVICE_HOST
          #   value: redis-master-clusterip
          # - name: REDIS_SLAVE_SERVICE_HOST
          #   value: redis-master-clusterip
      volumes:
      - name: config-volume
        configMap:
            name: example-configmap
