apiVersion: v1
kind: Service
metadata:
  name: redis-master-clusterip
spec:
  type: ClusterIP
  selector:
    app: redis-master
  ports:
    - name: http
      protocol: TCP
      port: 6379 # port i'm exposing locally
      targetPort: 6379 # port that loadbalancer attaching to