apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - name: redis-slave
          image: docker.artifactory.euw.platformservices.io/redis:3.2.9
          command: ["redis-server", "--slaveof", "redis-master", "6379"]
          ports:
          - containerPort: 6379