apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
        - name: redis-master
          image: docker.artifactory.euw.platformservices.io/redis:3.2.9
          ports:
          - containerPort: 6379